image: python:2.7

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

stages:
  - test

bandit:
  stage: test
  script:
    - make bandit

test:
  stage: test
  script:
    - make test
